apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  labels: 
    {{- include "helm-charts.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type}}
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 6}}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
    - protocol: TCP
      name: https
      port: 443
      targetPort: {{ .Values.service.targetPort}}